### ISSUE TITLE
can't build on GPU

### ISSUE THREAD

**Issue by taoyang1994** [theICTlab/3DUNDERWORLD-SLS-GPU_CPU#3]
The header file of  FileReaderCUDA.cuh, #include<core/FileReader.h>, I can not fond the file in the core folder.This is what problem?

**Comment by v3c70r** [comment]
Hi Taoyang,
Sorry for the inconvenience. The GPU implementation is under refactoring now and might be broken. It'll be fixed soon. But for now, you can check out this reversion 5982af61e410fecde7a102820579e7c3753b3c96. It should work properly.

**Comment by deepakbkar** [comment]
Hi v3c70r,
I do not see any change in the revision 5982af6 that would fix this error.
Any other suggestion?
Regards,
Deepak

**Comment by v3c70r** [comment]
@deepakbkar Sorry, the correct commit should be cdab27b7e076f1b0c83f0d0dba6bfd1c0d260f0a.

**Comment by yvhtswaroop** [comment]
The issue still persists and not addressed in commit (https://github.com/theICTlab/3DUNDERWORLD-SLS-GPU_CPU/commit/cdab27b7e076f1b0c83f0d0dba6bfd1c0d260f0a) shared above. There is no FileReader.h file in core.
